[phases.setup]
nixPkgs = ['nodejs_22']
nixpkgsArchive = 'ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7'

[phases.install]
dependsOn = ['setup']
cmds = [
  'cd backend',
  'npm ci --legacy-peer-deps'
]

[phases.build]
dependsOn = ['install']
cmds = [
  'cd backend',
  'npm run build'
]

[start]
cmd = 'sh -c "cd backend && node dist/main"'
